# Generated by Django 3.0.7 on 2020-06-16 04:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20200616_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='main_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
