# Generated by Django 3.0.7 on 2020-06-16 06:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20200616_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='body_side_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='body_text_1',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='body_text_2',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='body_text_3',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='body_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
