# Generated by Django 3.0.7 on 2020-06-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_auto_20200616_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='pic',
        ),
    ]
