# Generated by Django 3.0.7 on 2020-06-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_remove_points_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='gallery_image',
        ),
    ]
