# Generated by Django 3.0.7 on 2020-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
