# Generated by Django 3.0.7 on 2020-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='team_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
