# Generated by Django 3.0.7 on 2020-06-29 05:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0011_auto_20200629_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='side_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
