# Generated by Django 3.0.7 on 2020-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0012_auto_20200629_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='body_side_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='side_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
