# Generated by Django 3.0.7 on 2020-07-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('about_us', '0014_auto_20200706_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='history_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 440 px (width) x 540 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; Approximate dimension: 1440 px (width) x 360 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 95 px (width) x 90 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 300 px (width) x 300 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
