# Generated by Django 3.0.7 on 2020-06-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultansandpartners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultansandpartners',
            name='header_title',
        ),
    ]
