# Generated by Django 3.0.7 on 2020-06-15 12:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('consultansandpartners', '0002_remove_consultansandpartners_header_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultansandpartners',
            name='consultans_Partners_body',
            field=wagtail.core.fields.RichTextField(default=' ', help_text='Body', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='consultansandpartners',
            name='consultans_Partners_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
