# Generated by Django 3.0.7 on 2020-06-15 13:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultansandpartners', '0004_auto_20200615_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultansandpartners',
            name='consultans_Partners_body',
            field=wagtail.core.fields.RichTextField(default=' ', help_text='Body', max_length=1400, null=True),
        ),
        migrations.AlterField(
            model_name='consultansandpartners',
            name='idp_program_body',
            field=wagtail.core.fields.RichTextField(default=' ', help_text='Body', max_length=1400, null=True),
        ),
    ]
