# Generated by Django 3.0.7 on 2020-07-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('consultansandpartners', '0006_auto_20200706_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultansandpartners',
            name='consultans_Partners_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 465 px (width) x 425 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='consultansandpartners',
            name='idp_program_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 400 px (width) x 500 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
