# Generated by Django 3.0.7 on 2020-06-16 11:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='content_body',
            field=wagtail.core.fields.RichTextField(default=' ', help_text='Body', max_length=1400, null=True),
        ),
    ]
