# Generated by Django 3.0.7 on 2020-06-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20200616_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDeatils',
            new_name='ContactDetails',
        ),
    ]
