# Generated by Django 3.0.7 on 2020-06-11 16:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_promo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='vision_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write vision', null=True),
        ),
    ]
