# Generated by Django 3.0.7 on 2020-06-11 16:38

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200611_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='vision_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write vision', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_title',
            field=models.CharField(blank=True, help_text='Vision', max_length=100, null=True),
        ),
    ]
