# Generated by Django 3.0.7 on 2020-06-12 10:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0007_auto_20200611_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mission_title',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Mission title', max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('mission', models.CharField(blank=True, max_length=250)),
                ('list_label', models.ForeignKey(blank=True, help_text='List label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
