# Generated by Django 3.0.7 on 2020-06-12 14:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0009_auto_20200612_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='objectives_bg_image',
            field=models.ForeignKey(help_text='Background Image Of Objectives Section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='objectives_title',
            field=models.CharField(default='Objectives', help_text='Objective title', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ship_image_objectives',
            field=models.ForeignKey(help_text='Image displayed in the right side of objectives section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('objective_text', models.CharField(default='Enter Objective', max_length=250)),
                ('objective_image', models.ForeignKey(help_text='Images of Objectives', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
