# Generated by Django 3.0.7 on 2020-06-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0010_auto_20200612_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='objectives_bg_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='ship_image_objectives',
        ),
        migrations.AddField(
            model_name='homepage',
            name='objectives_background_image',
            field=models.ForeignKey(blank=True, help_text='Background Image Of Objectives Section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='objectives_side_image',
            field=models.ForeignKey(blank=True, help_text='Image displayed in the right side of objectives section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
