# Generated by Django 3.0.7 on 2020-06-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200612_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='objectives_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='objectives_side_image',
        ),
    ]
