# Generated by Django 3.0.7 on 2020-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200612_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='objective_text',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
