# Generated by Django 3.0.7 on 2020-06-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0014_auto_20200612_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(default='Mission', help_text='Mission title', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='objectives_background_image',
            field=models.ForeignKey(help_text='Background Image Of Objectives Section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='objectives_side_image',
            field=models.ForeignKey(help_text='Image displayed in the right side of objectives section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='list_label',
            field=models.ForeignKey(help_text='List label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
