# Generated by Django 3.0.7 on 2020-06-13 13:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0016_auto_20200613_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_us_button_text',
            field=models.CharField(blank=True, default='Contact with Us', help_text='Text displayed inside the contact us button', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_inside_contact_us_button',
            field=models.ForeignKey(blank=True, help_text='Arrow displayed inside the contact us button ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='usp_side_image',
            field=models.ForeignKey(help_text='Image to be displayed inside USP secton', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='usp_title',
            field=models.CharField(default='Our USP', help_text='USP section title', max_length=250),
        ),
        migrations.CreateModel(
            name='USP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('usp', models.CharField(default=' ', max_length=250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='usps', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
