# Generated by Django 3.0.7 on 2020-06-13 18:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0017_auto_20200613_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='list_label',
        ),
        migrations.AddField(
            model_name='homepage',
            name='download_image_for_brochure',
            field=models.ForeignKey(help_text='Download image displayed near brochure ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='download_text_with_brochure',
            field=models.CharField(blank=True, default='Click here to download', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_list_label',
            field=models.ForeignKey(help_text='List label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_support_item_image',
            field=models.ForeignKey(blank=True, help_text='Image diplayed in the left sideof support section ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='support_text',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='support_title',
            field=models.CharField(default='24X7 Support', max_length=250),
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('brochure_name', models.CharField(default=' ', max_length=400)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochure_list', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
