# Generated by Django 3.0.7 on 2020-06-14 09:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0020_auto_20200614_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.HomePage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_us_button_text',
            field=models.CharField(blank=True, default=' ', help_text='Text displayed inside the contact us button', max_length=250),
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
