# Generated by Django 3.0.7 on 2020-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200614_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_us_title',
            field=models.CharField(default='CONTACT US', max_length=250),
        ),
    ]
