# Generated by Django 3.0.7 on 2020-06-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_advert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
