# Generated by Django 3.0.7 on 2020-06-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
    ]
