# Generated by Django 3.0.7 on 2020-06-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_homepage_thank_you_text'),
        ('home', '0028_auto_20200630_1215'),
    ]

    operations = [
    ]
