# Generated by Django 3.0.7 on 2020-07-06 04:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0028_homepage_thank_you_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background_image_of_support',
            field=models.ForeignKey(blank=True, help_text='Background image of support text. Please upload PNG file with approximate dimensions 360 px (width) x 580 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='download_image_for_brochure',
            field=models.ForeignKey(help_text='Download icon for brochure. Please upload PNG file with approximate dimensions 26 px (width) x 26 px (height) ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 1440 px (width) x 640 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image_inside_contact_us_button',
            field=models.ForeignKey(blank=True, help_text='Arrow displayed inside the contact us button.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_list_label',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 17 px (width) x 13 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(default='Mission', help_text='Title section', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='objectives_background_image',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 1440 px (width) x 800 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='objectives_side_image',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 670 px (width) x 560 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_support_item_image',
            field=models.ForeignKey(blank=True, help_text='Image diplayed on the left side of support section. Please upload PNG file with approximate dimensions 360 px (width) x 580 px (height) ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='usp_side_image',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 410 px (width) x 570 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='usp_title',
            field=models.CharField(default='Our USP', help_text='Title section', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_image',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 137 px (width) x 137 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_text',
            field=wagtail.core.fields.RichTextField(default=' ', help_text='Text to display Vision', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_title',
            field=models.CharField(default='Vision', help_text='Title section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_image',
            field=models.ForeignKey(help_text='Please upload PNG file with approximate dimensions 52 px (width) x 54 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
