# Generated by Django 3.0.7 on 2020-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_merge_20200630_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thank_you_text',
            field=models.CharField(default='Thankyou. Your response has been submitted successfully.', max_length=2300),
        ),
    ]
