# Generated by Django 3.0.7 on 2020-07-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0031_auto_20200706_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background_image_of_support',
            field=models.ForeignKey(blank=True, help_text='Background image of support text. Use PNG file with approximate dimension 360 px (width) x 580 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='download_image_for_brochure',
            field=models.ForeignKey(help_text='Download icon for brochure. Use PNG file with approximate dimension 26 px (width) x 26 px (height) ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_list_label',
            field=models.ForeignKey(help_text='PNG file with approximate dimension 17 px (width) x 13 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='objectives_background_image',
            field=models.ForeignKey(help_text='PNG file with approximate dimension 1440 px (width) x 800 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='objectives_side_image',
            field=models.ForeignKey(help_text='PNG file with approximate dimension 670 px (width) x 560 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_support_item_image',
            field=models.ForeignKey(blank=True, help_text='Image diplayed on the left side of support section. Use PNG file with approximate dimension 360 px (width) x 580 px (height) ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='usp_side_image',
            field=models.ForeignKey(help_text='PNG file with approximate dimension 410 px (width) x 570 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_image',
            field=models.ForeignKey(help_text='PNG file with approximate dimension 137 px (width) x 137 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_image',
            field=models.ForeignKey(help_text='PNG file with approximate dimension 52 px (width) x 54 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
