# Generated by Django 3.0.7 on 2020-07-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200706_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
    ]
