# Generated by Django 3.0.7 on 2020-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_homepage_thank_you_text'),
        ('home', '0030_homepage_thank_you_text'),
    ]

    operations = [
    ]
