# Generated by Django 3.0.7 on 2020-07-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_merge_20200706_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
    ]
