# Generated by Django 3.0.7 on 2020-07-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_homepage_thank_you_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thank_you_text',
            field=models.CharField(default='Thankyou. Your response has been submitted successfully.', max_length=2300),
        ),
    ]
