# Generated by Django 3.0.7 on 2020-06-18 10:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('industry_directions', '0004_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydirectionspage',
            name='base_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrydirectionspage',
            name='base_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
