# Generated by Django 3.0.7 on 2020-06-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('industry_directions', '0005_auto_20200618_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydirectionspage',
            name='chart_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='industrydirectionspage',
            name='chart_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='industrydirectionspage',
            name='chart_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
