# Generated by Django 3.0.7 on 2020-06-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('industry_directions', '0007_growthchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthchart',
            name='growth_image',
        ),
        migrations.AddField(
            model_name='growthchart',
            name='svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
