# Generated by Django 3.0.7 on 2020-06-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('industry_directions', '0009_auto_20200622_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthchart',
            name='link_url',
        ),
        migrations.AddField(
            model_name='growthchart',
            name='svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
