# Generated by Django 3.0.7 on 2020-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('industry_directions', '0010_auto_20200622_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthchart',
            name='svg',
        ),
        migrations.AddField(
            model_name='growthchart',
            name='growth_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
