# Generated by Django 3.0.7 on 2020-07-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('industry_directions', '0011_auto_20200622_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrydirectionspage',
            name='chart_background',
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='body_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimensions: 380 px (width) x 250 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimensions: 490 px (width) x 390 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='chart_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimensions: 570 px (width) x 500 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; Approximate dimensions: 1440 px (width) x 360 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
