# Generated by Django 3.0.7 on 2020-07-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('industry_directions', '0012_auto_20200706_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='body_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 380 px (width) x 250 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 490 px (width) x 390 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='chart_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 570 px (width) x 500 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='industrydirectionspage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; Approximate dimension: 1440 px (width) x 360 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='points',
            name='point_image',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 120 px (width) x 120 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
