# Generated by Django 3.0.7 on 2020-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_about', models.CharField(max_length=150)),
                ('enquiry_mail', models.CharField(max_length=150)),
            ],
        ),
    ]
