# Generated by Django 3.0.7 on 2020-06-24 06:39

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20200619_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
