# Generated by Django 3.0.7 on 2020-06-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_footer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='slug',
        ),
    ]
