# Generated by Django 3.0.7 on 2020-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20200626_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='sub_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
