# Generated by Django 3.0.7 on 2020-07-04 12:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_submenu_sub_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='xport_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Short description displayed below the logo in footer', max_length=1000, null=True),
        ),
    ]
