# Generated by Django 3.0.7 on 2020-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsmanagementpage',
            name='operations_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
