# Generated by Django 3.0.7 on 2020-06-16 11:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operationsmanagementpage_operations_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsmanagementpage',
            name='operations_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
