# Generated by Django 3.0.7 on 2020-06-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20200616_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='image',
            new_name='pic',
        ),
    ]
