# Generated by Django 3.0.7 on 2020-06-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('operations', '0007_management2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management1',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='management1',
            old_name='title',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='management1',
            old_name='pic',
            new_name='pic1',
        ),
        migrations.AddField(
            model_name='management1',
            name='pic2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='management1',
            name='title1',
            field=models.TextField(blank=True, help_text='Text', null=True),
        ),
        migrations.AddField(
            model_name='management1',
            name='title2',
            field=models.TextField(blank=True, help_text='Text', null=True),
        ),
        migrations.DeleteModel(
            name='Management2',
        ),
    ]
