# Generated by Django 3.0.7 on 2020-06-17 05:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20200617_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management1',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='management1',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='management1',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_field', to='operations.OperationsManagementPage'),
        ),
        migrations.AlterField(
            model_name='management1',
            name='title1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='management1',
            name='title2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
