# Generated by Django 3.0.7 on 2020-07-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('operations', '0010_auto_20200706_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management1',
            name='pic1',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 510 px (width) x 410 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='management1',
            name='pic2',
            field=models.ForeignKey(blank=True, help_text='Approximate dimension: 510 px (width) x 410 px (height)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
